---
title: Laravel & Vue.js Developer - Roger Vilà
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title"
- scope:
    path: assets/**
  values:
    sitemap: false
repository: rogervila/rogervila.github.io
cloudinary:
  base: https://res.cloudinary.com/rogervila/image/upload/
chatra:
  id: DMxNajG68hYYtyPsd
commentbox_io:
  id: 5674748138749952-proj
google_analytics:
  id: UA-55617377-1
cookiebot:
  id: 81f0d276-2838-45b4-88c7-634ca8b9a658
lang: en
description: Roger Vilà is a developer specialized on web applications build on top
  of laravel framework.
url: https://rogervila.es
author: _rogervila
twitter:
  username: _rogervila
  card: summary
  hashtag: rogervila
github:
  username: rogervila
linkedin: https://es.linkedin.com/in/rogervilacamon
logo: https://res.cloudinary.com/rogervila/image/upload/f_auto,q_auto:best,w_112,h_28,c_lpad,b_white,dpr_auto/logo_qqflde
social:
  name: Roger Vilà
  links:
  - https://github.com/rogervila
  - https://twitter.com/_rogervila
webmaster_verifications:
  google: X3uvg5AB1-UMV9MBVlvSylNxOc93YJlO1Pq4uBb588A
  bing: B78749ACD39E931F3E7367CCB8D8430C
paginate: 9
paginate_path: "/blog/page/:num/"
sass:
  sass_dir: _sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- Dockerfile
- docker-compose.yml
- ".editorconfig"
- ".gitignore"
- ".dockerignore"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-gist
- jekyll-github-metadata
