---
---

---
title: Roger Vilà
url: http://rogervila.github.io.dev/
exclude: ['package.json', 'package-lock.json', 'webpack.mix.js', 'node_modules','vendor','Gemfile','Gemfile.lock','mix-manifest.json','LICENSE']
timezone: Europe/Madrid
cloudinary:
  url: 'https://res.cloudinary.com/rogervila/image/upload/f_auto,q_auto,dpr_auto,w_auto,c_scale,g_auto/'
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
  - jekyll-sitemap
