---
title: Senior Backend Developer - Roger Vilà
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: default
    permalink: "/blog/:title"
    is_post: true
- scope:
    path: assets/**
  values:
    sitemap: false
blog: https://rogervila.medium.com/
repository: rogervila/rogervila.github.io
instant_page: false
cloudinary:
  base: https://res.cloudinary.com/rogervila/image/upload/
lang: en
description: Roger Vilà is a Experienced Senior Backend Developer with 10+ years expertise
  in building backend systems with Laravel, Symfony, PHP, Javascript and Python
url: https://rogervila.es
author:
  twitter: _rogervila
twitter:
  username: _rogervila
  card: summary
  hashtag: rogervila
stackoverflow:
  profile: https://stackoverflow.com/users/3333549/rogervila
github:
  username: rogervila
linkedin: https://es.linkedin.com/in/rogervilacamon
logo: https://res.cloudinary.com/rogervila/image/upload/f_auto,q_auto:best,w_112,h_28,c_lpad,b_white,dpr_auto/logo_qqflde
logo_srcset: https://res.cloudinary.com/rogervila/image/upload/f_auto,q_auto:best,w_224,h_56,c_lpad,b_white,dpr_auto/logo_qqflde
  2x
social:
  name: Roger Vilà
  links:
  - https://github.com/rogervila
  - https://twitter.com/_rogervila
webmaster_verifications:
  google: X3uvg5AB1-UMV9MBVlvSylNxOc93YJlO1Pq4uBb588A
  bing: B78749ACD39E931F3E7367CCB8D8430C
paginate: 9
paginate_path: "/blog/page/:num/"
sass:
  sass_dir: _sass
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- Dockerfile
- docker-compose.yml
- ".editorconfig"
- ".gitignore"
- ".dockerignore"
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-gist
- jekyll-github-metadata
