---
title: Laravel, Vue.js, React, Angular - Roger Vilà
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://rogervila.es
exclude:
- package.json
- package-lock.json
- webpack.mix.js
- node_modules
- vendor
- Gemfile
- Gemfile.lock
- mix-manifest.json
- LICENSE
- Dockerfile
- docker-compose.yml
- dev.sh
- staging.sh
- Dockerfile-development
- docker-compose.development.yml
cloudinary:
  url: https://res.cloudinary.com/rogervila/image/upload/f_auto,q_auto,dpr_auto,w_auto,c_scale,g_auto/
plugins:
- jekyll-sitemap
