version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers # Make sure your image has both `node` and is able to launch a browser
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Build the site
          command: bundle exec jekyll build
      - run:
          name: Visual Tests
          command: npx percy snapshot _site # snapshot built Jekyll site
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - test
